name: PistonNC
version: ${project.version}
main: net.pistonmaster.namecolor.PistonNC
api-version: 1.13
authors: ["Nate Legault", "AlexProgrammerDE"]
description: ${project.description}
website: ${project.url}
commands:
  nc:
    description: Change your name color.
    aliases: [namecolor, namecolour]
  ic:
    description: Change your item color.
    aliases: [itemcolor, itemcolour]
permissions:
  piston.nc:
    description: Gives access to changing name color via the /nc command
  piston.ic:
    description: Gives access to changing item color via the /ic command