name: LeeesNC
version: 10.0.2
main: leee.nc.Main
api-version: 1.12
authors: [Nate, Legault]
description: Leees Name Colour Plugin
website: https://www.6b6t.org
commands:
  nc:
    description: Change your name color.
    aliases: [namecolor, namecolour]
permissions:
  Leee.nc:
    description: Gives access to changing name color via the /nc command